name: 🐛 Bug Report
description: Create a report to help us improve AluVerse
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I click on the alumni search button, the page crashes...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The search should filter alumni without crashing...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: The page crashes with a JavaScript error...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information.
      placeholder: |
        - OS: [e.g. Windows 10]
        - Browser: [e.g. Chrome 120]
        - App Version: [e.g. 1.0.0]
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (cosmetic issue)
        - Medium (feature works but with issues)
        - High (feature broken)
        - Critical (app unusable)
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting.
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided all requested information
          required: true
        - label: This is not a duplicate issue
          required: true
